version: '3.8'

services:
  evaluation:
    image: evaluation_app_image
    container_name: evaluation_app
    build:
      context: .
      dockerfile: ./evaluation/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    env_file: .env

  rag_pipeline:
    image: rag_pipeline_image
    container_name: rag_pipeline
    build:
      context: .
      dockerfile: ./rag-pipeline/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - db
      - graphdb
    env_file: .env

  ui:
    image: streamlit_ui_image
    container_name: streamlit_app
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - 8503:8501
    env_file: ./ui/.env

  db:
    image: mongodb/mongodb-community-server:latest
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 29019:27017

  graphdb:
    image: neo4j:latest
    environment:  
      - NEO4J_AUTH=none
      - NEO4J_dbms_security_auth__enabled=false
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
    ports:
      - 7674:7474
      - 7887:7687

volumes:
  mongo_data:
  neo4j_data:
