version: '3.8'

services:
  app:
    image: tiangolo/uvicorn-gunicorn-fastapi:latest
    container_name: evaluation_app
    build:
      context: .
      dockerfile: ./evaluation/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    env_file: .env

  db:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_db
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 29019:27017

volumes:
  mongo-data:
